project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: About
      # - about.qmd
      - href: CV/index.qmd 
        text: CV
      - href: gallery.qmd
        text: Gallery
      - href: note_book/index.qmd
        text: Notebook
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

